name: Deploy fdz-api (DockerHub, DigitalOcean)
on:
  push:
    branches: [main]
    tags: 
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v1
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/fdz-api
          tag-sha: true 

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Bump version and push tag
        id: tagging
        uses: mathieudutour/github-tag-action@v5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          plataform: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/fdz-api:${{ steps.tagging.outputs.new_version }}
          labels: ${{ steps.docker_meta.outputs.labels }}
      
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_TOKEN }}

      - name: Setup kubectl
        uses: matootie/dokube@v1.4.0
        with:
          personalAccessToken: ${{ secrets.DIGITALOCEAN_TOKEN }}
          clusterName: k8s-friendzou

      - name: Set deployment image
        run: |
          kubectl set image deployment fdz-api fdz-api=${{ secrets.DOCKER_USERNAME }}/fdz-api:${{ steps.tagging.outputs.new_version }}
